### ISSUE TITLE
Python script is stuck because he "wait_for_server_response"

### ISSUE THREAD

**Issue by ghost** [donadigo/TMInterfaceClientPython#11]
Hi @donadigo,

First of all, I wanted to thank you for the great work you did with TMinterface.

I wanted to use the TMInterfaceClientPython to work with the position/velocity of the car and to be able to control it with a neural network. I'm actually able to get the position of the car, and did manage to control it but it's quite unstable.
I'm not sure I'm using the tool the right way because my script is often stuck (75% of the time). It seems that he's "waiting for the server response" forever.

Here you can find a part of my script :

```
# -*- coding: utf-8 -*-

import time
from colors import bcolors
from random import randint

from tminterface.client import Client
from tminterface.interface import TMInterface
from tminterface.commandlist import TimedCommand 



def add_position(C,Lx,Ly,Lz,T):
    data=C.get_simulation_state()
    position=data.position
    Lx.append(round(position[0]))
    Ly.append(round(position[1]))
    Lz.append(round(position[2]))
    T.append(data.race_time)
    
   
def going_direction(direction,time,time_ending):
    print(bcolors.green+"going "+direction+bcolors.reset)
    str_time=str(time)+'-'+str(time_ending)
    input_car=TimedCommand(["press "+direction],str_time,True)
    C.execute_command(input_car.to_script())


  
def succession_command():
    rand_direction=randint(1,2)
    rand1=randint(100,400)*10
    rand2=randint(200,300)*10
    rand3=randint(100,500)*10
    going_direction("up",130,rand1)
    if rand_direction==1:
        going_direction("left",rand2,rand3)
    else:
        going_direction("right",rand2,rand3)
  
if __name__=="__main__":
    ##Initialize
    print(bcolors.green+"Starting"+bcolors.reset)
    C=TMInterface("TMInterface1")
    time.sleep(1)
    A=Client()
    if C.register(A)==True:
        print(bcolors.magenta+"sucessfully register a new client"+bcolors.reset)
    else: print(bcolors.red+"Already registered"+bcolors.reset)  
    
    
    ##Unload previous commands 
    time.sleep(2)
    C.execute_command("unload")
    
    ##Sending commands
    time.sleep(2)
    succession_command()
     
    ##Respawn 
    time.sleep(2)
    C.respawn()
    
    ##Closing the client
    time.sleep(0.5)  
    print(bcolors.red+"Finishing"+bcolors.reset)
    C.close()
    time.sleep(0.5)
    
    
    ##Recording the position of the car
    Lx=[]
    Ly=[]
    Lz=[]
    T=[]
    print(bcolors.yellow+"go"+bcolors.reset)
    for i in range(100):
        time.sleep(0.01)
        add_position(C,Lx,Ly,Lz,T)

````
  
Note that the client in python script always manage to connect to the TMInterface, as the TMInterface consol always display "Registered new client". However, the execution of this python script is more and less fast and can be stuck for example, in the lines: 

```
line 26, in going_direction
    C.execute_command(input_car.to_script())
```
or
```
line 54, in <module>
    C.execute_command("unload")
```

By the way, I noticed that when the python script is stuck and that I manually deregister the client from the TMInterface console, the script get unstuck, and the command that weren't executed get executed.

Do you have any idea why this happens ?

**Comment by donadigo** [comment]
Hey, take a look at the `examples` directory in the repo to see how to correctly setup a `MainClient` class which should be used to receive all events from TMInterface: https://github.com/donadigo/TMInterfaceClientPython/tree/master/examples. The approach you took here won't work as the connection is designed to be synchronous - that is TMI will wait for your response until you return from one of the functions declared in your MainClient class. 

The gist of it is that you create a new class subclassing the `Client` and then implement the hooks you want receive in the class. You then register an instance of your class on the server, like here for example: https://github.com/donadigo/TMInterfaceClientPython/blob/master/examples/restore_state.py

There's also ReadTheDocs documentation on what API's the current package provides: https://tminterface.readthedocs.io/en/latest/source/tminterface.html

Because the code inside the Client class runs in another thread, you can run some other code you need alongside it, be aware however that all calls to `iface` need to be done in the Client class, not anywhere else. Here's an example: https://github.com/donadigo/TMInterfaceClientPython/blob/master/examples/process_async.py

**Comment by ghost** [comment]
Hi,
Thank you for the answer.
I didn't see the example folder before posting my question and I don't understand how I managed not seeing it.
I'll continue working with the example you provided, thanks !
